name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY }}
      PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      RESEND_FROM_EMAIL: ${{ secrets.RESEND_FROM_EMAIL }}
      RESEND_FROM_NAME: ${{ secrets.RESEND_FROM_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required secrets
        shell: bash
        run: |
          set -euo pipefail
          missing=()
          required=(
            NEXT_PUBLIC_SUPABASE_URL
            NEXT_PUBLIC_SUPABASE_ANON_KEY
            NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
            PAYSTACK_SECRET_KEY
            RESEND_API_KEY
            RESEND_FROM_EMAIL
            RESEND_FROM_NAME
          )
          for v in "${required[@]}"; do
            if [ -z "${!v:-}" ]; then
              echo "::error title=Missing secret::$v is not set (add it in Settings → Secrets and variables → Actions)"
              missing+=("$v")
            fi
          done
          if [ "${#missing[@]}" -gt 0 ]; then
            echo "Missing ${#missing[@]} secret(s): ${missing[*]}"
            exit 1
          else
            echo "✅ All required secrets are present."
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build
